#########################
#  CUBE HOMES by Rayzr  #
# Requested by xOrlxndo #
#########################

permissions:
    home: "CubeHomes.home"
    more: "CubeHomes.more"
    others: "CubeHomes.others"
    sethome: "CubeHomes.sethome"
    delhome: "CubeHomes.delhome"
    cubehomes: "CubeHomes.admin"