name: CubeHomes
main: com.rayzr522.cubehomes.CubeHomes
version: 0.1
description: Customizable homes plugin
commands:
  home:
    description: Go to one of your homes
  sethome:
    description: Set a home
  delhome:
    description: Delete a home
  warp:
    description: Go to one of the warps
  setwarp:
    description: Set a warp
  warpicon:
    description: Set a warp's icon
  delwarp:
    description: Delete a warp
  cubehomes:
    description: Management commands for CubeHomes